name: Deploy Matrix Email

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH Connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        port: 8264
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
           cd ams-apps
           echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop matrixEmail
           if [ -d "matrix-email" ]; then rm -rf "matrix-email"; fi
           git clone -b master --single-branch https://github.com/AMS-Pvt-Ltd/matrix-email.git
           cd matrix-email
           chmod +x ./mvnw
           ./mvnw clean compile install package
           echo "${{ secrets.PASSWORD }}" | sudo -S systemctl start matrixEmail
